server {
    listen 127.0.0.1:8088;
    server_name "sunls.me";

    charset utf-8;
    access_log off;
    server_tokens off;
    disable_symlinks off;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/xml text/css application/javascript application/json;

    add_header cache-control "no-cache";
    add_header access-control-allow-origin "*";
    add_header referrer-policy "no-referrer";
    add_header x-content-type-options nosniff;
    add_header x-xss-protection "1; mode=block";
    add_header x-frame-options sameorigin;
    add_header x-robots-tag "noindex, nofollow";

    root /home/sunls/fs;

    location ~ ^/x(/|/.+/)$ {
        auth_basic "Private Folder";
        auth_basic_user_file /home/sunls/.fspasswd;

        autoindex on;
        autoindex_localtime on;
        autoindex_exact_size off;
        add_after_body /.hide/autoindex.html;
    }

    location ~ ^(.*)/$ {
        autoindex on;
        autoindex_localtime on;
        autoindex_exact_size off;
        add_after_body /.hide/autoindex.html;
    }

    location = /robots.txt {
        default_type text/plain;
        set $robots "User-agent: *\nDisallow: /";
        if ($http_user_agent ~* "^Wget") {
            set $robots "";
        }
        return 200 $robots;
    }

    location ~ \.md$ {
        default_type text/html;
        add_after_body /.hide/markdown.html;
    }

    location ~* \.(ico|css|js|gif|jpeg|jpg|png|woff|ttf|otf|svg|woff2|eot)$ {
        expires 1d;
        access_log off;
        add_header Pragma public;
    }

    location ~ \.(log|pac|keys|lua|json|yaml|toml|conf|cmd|sh|bash|h|c|cpp|hpp|py|go|service)$ {
        default_type text/plain;
    }

    location ~ ^/(bashrc|vimrc)$ {
        default_type text/plain;
    }

    location =/404 {
        default_type "text/html";
        alias /home/sunls/sunls.me/html/404.html;
    }
}
